#!/usr/bin/env bash
set -e

_term() {
  >&2 echo "TERM while go mod download"
  trap '' TERM
  kill -- $$
  exit 0
}


if [ "$1" = "" ]; then
  echo "usage:"
  echo 'CMD [ "go run main.go" ]'
  sleep 1
  exit 1
fi

exec reflex -s $@
