#!/usr/bin/env sh
set -e

if [ "$1" = "" ]; then
  echo "usage:"
  echo 'CMD [ "go run main.go" ]'
  sleep 1
  exit 1
fi

echo "go mod download starting"
go mod download
echo "go mod download completed"
exec reflex -s $@
