name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: mattipaksula
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v2
    - run: |
        docker-compose build
        docker-compose push
