name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: mattipaksula
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mattipaksula/reflux
          tag_with_ref: true
          tag_with_sha: true
        env:
          DOCKER_BUILDKIT: 1
